# Generated by Django 4.1.5 on 2023-03-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_signup_day_alter_user_signup_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_day',
            field=models.CharField(default=26, max_length=50),
        ),
    ]
