# Generated by Django 4.1.5 on 2023-05-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_signup_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_day',
            field=models.CharField(default=10, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup_month',
            field=models.CharField(default=5, max_length=50),
        ),
    ]
