# Generated by Django 4.1.5 on 2023-04-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on delivery'), ('Razorpay', 'Razorpay')], default='cash_on_delivery', max_length=20),
        ),
    ]
