# Generated by Django 4.1.5 on 2023-04-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_shipping_cost_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
