# Generated by Django 4.1.5 on 2023-05-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_orderitem_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
