# Generated by Django 4.1.5 on 2023-04-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_email_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip_code',
        ),
    ]
